version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda-go"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-icqk9ib4so0j"
s3_prefix = "sam-lambda-go"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
